[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "netmapper-z"
version = "1.0.0"
description = "Hybrid reconnaissance framework for active and passive network mapping."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
dependencies = [
    "requests==2.31.0",
    "python-nmap==0.7.1",
    "python-whois==0.8.0",
    "urllib3==2.0.4"
]

[project.scripts]
nmz = "nmz:main"
